apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: regfruit.azurecr.io/be:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: '0'
            memory: '0'
          limits:
            cpu: '0.5'
            memory: 0.5G
    imagePullSecrets:
        - name: regsec
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
